exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty

# Setup
title:            Microwave Media
logo:             logo.png
tagline:          'Heating brands from the inside out.'
description:      'A boutique London-based web-design and development agency setup by <a href="http://www.alexchin.co.uk" title="Alex Chin">Alex Chin</a>, <a href="http://problemsolvedux.com/" title="Andrew Wills">Andrew Wills</a> and <a href="http://fa-designer.com/" title="Fernando Amschlinger">Fernando Amschlinger</a>.'
url:              http://localhost:4000/
# baseurl:          http://localhost:4000/
paginate:         1

author:
  name:           'Alex Chin'
  url:            https://twitter.com/alexpchin

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/alexpchin

blogs:
 alex:            http://www.alexchin.co.uk

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true
